### ISSUE TITLE
Fader values always zero

### ISSUE THREAD

**Issue by tjahnks23** [jgrooms/x32dotnet#1]
I would like to add to the current value of any fader. It seems you cannot perform a "+=" to increment a fader's value. It is always zero even though the fader is initially at a different value. How do I get any current faders' values?

**Comment by jgrooms** [comment]
The library does not "sync" to the console by default so all the values are zero until you read them from the console.  So to answer your question, you must retrieve the initial value from the console at some point and then add to it.

**Comment by tjahnks23** [comment]
Thank you for the quick reply, Jason! Any idea on how to achieve this? I do not see any read or get value methods.

**Comment by jgrooms** [comment]
The library is all event based so review all the methods starting with “On”.  As things happen on the console events are fired in the library and you simple respond.

To request a value there is a method, whose name is alluding me st the moment, I think name RequestParamter.  You pass the object reference to the parameter you are interested in.

It’s been a few years since I’ve worked on the library and I’m not at a computer to give you the specifics but they should get you going.

**Comment by jgrooms** [comment]
If someone wanted to extend the library a “sync” method that kicked off in a background thread and fired an event upon completion would be a nice add.  I wanted to add this but haven’t gotten to it.

**Comment by jgrooms** [comment]
Actually take a look at ControlRequest()

**Comment by jgrooms** [comment]
And “OnChannelFade”

**Comment by tjahnks23** [comment]
I'll take a look. Thanks for the info!

**Comment by tjahnks23** [comment]
ControlRequest() seems to be the only thing close because it performs an "Inquire", however, it is a void method. There is a SendToProtocol() method that also a void return. I wish I was smart enough to contribute and figure something out.

**Comment by jgrooms** [comment]
Yes it is void because the request is done asynchronous.  Your result should come back to you in the OnChannelFade event.

**Comment by tjahnks23** [comment]
Hey, how is the physical set up for communication to the X32? Can these messages be sent via wireless network? or would you need to connect and open a port via USB from computer to X32 console? 

I recently wrote a MIDI translator as a Windows form app to work with my two Akai APC20's and my lighting program, Daslight. I have since rekindled this old X32 need to work with one of my APC20's.

**Comment by jgrooms** [comment]
The connection is set up via ethernet not usb.  Wireless should be fine.

Jason

**Comment by tjahnks23** [comment]
UPDATE: never mind - I had one of my assemblies and namespaces the same as x32DotNet (stupid move on my part). _What .NET version is the package capable of running on? I'm getting an exception: An unhandled exception of type 'System.TypeLoadException' occurred in x32dotnet.dll_

**Comment by jgrooms** [comment]
It's been about 5 years since I compiled it so don't recall the exact
dependency.  However the source is available on Git Hub and can be
recompiled if necessary.
